"""Add recipe rating and review system

Revision ID: 8171d8e12f44
Revises: 8b81d68fe0fc
Create Date: 2025-10-28 00:05:52.812131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8171d8e12f44'
down_revision: Union[str, None] = '8b81d68fe0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.alter_column('ingredients', 'vitamin_c',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'vitamin_a',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'vitamin_e',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'vitamin_k',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'thiamine',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'riboflavin',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'niacin',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'folate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'magnesium',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'zinc',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'selenium',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'potassium',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'phosphorus',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'omega_3',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'omega_6',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('meal_plan_meals', 'recipe_details',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('meal_plan_meals', 'cuisine',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('nutritional_logs', 'vitamin_c',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'vitamin_a',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'vitamin_e',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'vitamin_k',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'thiamine',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'riboflavin',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'niacin',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'folate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'magnesium',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'zinc',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'selenium',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'potassium',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'phosphorus',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'omega_3',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'omega_6',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('recipes', 'per_serving_calories',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('recipes', 'per_serving_protein',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('recipes', 'per_serving_carbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('recipes', 'per_serving_fat',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('recipes', 'per_serving_sodium',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('recipes', 'total_calories',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('recipes', 'total_protein',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('recipes', 'total_carbs',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('recipes', 'total_fat',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('recipes', 'total_sodium',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('user_achievements', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.alter_column('user_nutrition_preferences', 'snacks_per_day',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_nutrition_preferences', 'snacks_per_day',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.alter_column('user_achievements', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('recipes', 'total_sodium',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('recipes', 'total_fat',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('recipes', 'total_carbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('recipes', 'total_protein',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('recipes', 'total_calories',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('recipes', 'per_serving_sodium',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('recipes', 'per_serving_fat',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('recipes', 'per_serving_carbs',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('recipes', 'per_serving_protein',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('recipes', 'per_serving_calories',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('nutritional_logs', 'omega_6',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'omega_3',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'phosphorus',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'potassium',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'selenium',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'zinc',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'magnesium',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'folate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'niacin',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'riboflavin',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'thiamine',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'vitamin_k',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'vitamin_e',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'vitamin_a',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('nutritional_logs', 'vitamin_c',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('meal_plan_meals', 'cuisine',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('meal_plan_meals', 'recipe_details',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ingredients', 'omega_6',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'omega_3',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'phosphorus',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'potassium',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'selenium',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'zinc',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'magnesium',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'folate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'niacin',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'riboflavin',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'thiamine',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'vitamin_k',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'vitamin_e',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'vitamin_a',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('ingredients', 'vitamin_c',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.alter_column('achievements', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
