"""Add dietary preferences and fitness assessment fields

Revision ID: 8b81d68fe0fc
Revises: 001
Create Date: 2025-08-16 14:21:50.548529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b81d68fe0fc'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('activity_logs', 'activity_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('activity_logs', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('health_profiles', sa.Column('dietary_preferences', sa.String(), nullable=True))
    op.add_column('health_profiles', sa.Column('dietary_restrictions', sa.String(), nullable=True))
    op.add_column('health_profiles', sa.Column('meal_preferences', sa.String(), nullable=True))
    op.add_column('health_profiles', sa.Column('current_endurance_minutes', sa.Integer(), nullable=True))
    op.add_column('health_profiles', sa.Column('pushup_count', sa.Integer(), nullable=True))
    op.add_column('health_profiles', sa.Column('squat_count', sa.Integer(), nullable=True))
    op.alter_column('health_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('health_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('health_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('metrics_history', 'health_profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metrics_history', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('metrics_history', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('metrics_history', 'health_profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('health_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('health_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('health_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('health_profiles', 'squat_count')
    op.drop_column('health_profiles', 'pushup_count')
    op.drop_column('health_profiles', 'current_endurance_minutes')
    op.drop_column('health_profiles', 'meal_preferences')
    op.drop_column('health_profiles', 'dietary_restrictions')
    op.drop_column('health_profiles', 'dietary_preferences')
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('activity_logs', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activity_logs', 'activity_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('activity_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
